backend:
  name: github
  repo: axelboc/website-rmittkd
  branch: make-static

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/content/home.md"
        label: "Homepage"
        name: "home"
        fields:
          - {label: "Intro", name: "body", widget: "markdown"}
          - {label: "\"Train with us\" section intro", name: "trainIntro", widget: "markdown"}
          - label: "Locations"
            name: "locations"
            widget: "list"
            fields:
              - {label: "Suburb", name: "title", widget: "string", pattern: ['^[A-Z]', "Should be capitalised"]}
              - {label: "Address", name: "address", widget: "string"}
              - label: "Session times"
                name: "times"
                widget: "list"
                fields:
                  - {label: "Days", name: "days", widget: "string"}
                  - label: "From (time)"
                    name: "from"
                    widget: "string"
                    pattern: ['^(1[0-2]|[1-9]):[0-5]?[0-9] [ap]m$', "Should be a time ofthe form: 6:30 pm"]
                  - label: "To (time)"
                    name: "to"
                    widget: "string"
                    pattern: ['^(1[0-2]|[1-9]):[0-5]?[0-9] [ap]m$', "Should be a time ofthe form: 6:30 pm"]
          - {label: "\"Membership fees\" section intro", name: "feesIntro", widget: "markdown"}
          - label: "Fees (RMIT student)"
            name: "studentFees"
            widget: "object"
            fields:
              - label: "Year"
                name: "year"
                widget: "number"
                valueType: "int"
                min: 0
              - label: "Semester"
                name: "semester"
                widget: "number"
                valueType: "int"
                min: 0
          - label: "Fees (public)"
            name: "publicFees"
            widget: "object"
            fields:
              - label: "Year"
                name: "year"
                widget: "number"
                valueType: "int"
                min: 0
              - label: "Semester"
                name: "semester"
                widget: "number"
                valueType: "int"
                min: 0
      - file: "src/content/tkd.md"
        label: "What is Taekwon-Do?"
        name: "tkd"
        fields:
          - {label: "Intro", name: "body", widget: "markdown"}
          - label: "Video"
            name: "video"
            widget: "string"
            pattern: ['^https:\/\/youtu\.be\/', "Should be a URL starting with: https://youtu.be/"]
      - file: "src/content/dojang.md"
        label: "Our Dojang"
        name: "dojang"
        fields:
          - {label: "Intro", name: "body", widget: "markdown"}
          - {label: "\"Instructors\" section intro", name: "instructorsIntro", widget: "markdown"}
          - label: "Instructors list"
            name: "instructors"
            widget: "list"
            fields:
              - {label: "Name", name: "title", widget: "string"}
              - label: "Black-belt degree (1-9)"
                name: "degree"
                widget: "number"
                valueType: "int"
                min: 1
                max: 9
                default: 1
              - {label: "Short biography", name: "bio", widget: "markdown"}
          - {label: "\"Associated clubs\" section intro", name: "clubsIntro", widget: "markdown"}
          - label: "Clubs list"
            name: "clubs"
            widget: "list"
            fields:
              - {label: "Club name", name: "name", widget: "string"}
              - {label: "Location", name: "location", widget: "string"}
              - {label: "In Greater Melbourne?", name: "melbourne", widget: "boolean"}
              - label: "State"
                name: "state"
                widget: "select"
                options: ["VIC", "NSW", "TAS", "QLD", "NT", "WA"]
                default: "VIC"
              - label: "Website"
                name: "web"
                widget: "string"
                required: false,
                pattern: ['^https:\/\/www\.facebook\.com\/', "Should be a URL starting with: https://www.facebook.com/"]
              - label: "Facebook"
                name: "fb"
                widget: "string"
                required: false,
                pattern: ['^https?:\/\/', "Should be a URL starting with: https:// or http://"]
