backend:
  name: github
  repo: axelboc/website-rmittkd
  branch: master

media_folder: "content/assets"
public_folder: "/assets"

collections:
  - name: "section"
    label: "Content Section"
    folder: "content/sections"
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "instructor"
    label: "Instructor"
    folder: "content/instructors"
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Degree", name: "degree", widget: "number" }
      - { label: "Description", name: "description", widget: "markdown" }
